// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_02t5aoIlu6Tk-Aq1haDdU_VVc8i9kxU',
    appId: '1:969831362695:web:54d26da5b73775c4108822',
    messagingSenderId: '969831362695',
    projectId: 'lacrooseapp',
    authDomain: 'lacrooseapp.firebaseapp.com',
    storageBucket: 'lacrooseapp.firebasestorage.app',
    measurementId: 'G-E33XEGC4TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB14ZIWiCcYdyHsYCTf7EAc2ReD-QCavPU',
    appId: '1:969831362695:android:230e086fd8652901108822',
    messagingSenderId: '969831362695',
    projectId: 'lacrooseapp',
    storageBucket: 'lacrooseapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfQm7mzcd3lRyJcSV0iZNUC4kmyqgc-mo',
    appId: '1:969831362695:ios:760838c5fb92394a108822',
    messagingSenderId: '969831362695',
    projectId: 'lacrooseapp',
    storageBucket: 'lacrooseapp.firebasestorage.app',
    iosBundleId: 'com.Toq.lacrosseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfQm7mzcd3lRyJcSV0iZNUC4kmyqgc-mo',
    appId: '1:969831362695:ios:760838c5fb92394a108822',
    messagingSenderId: '969831362695',
    projectId: 'lacrooseapp',
    storageBucket: 'lacrooseapp.firebasestorage.app',
    iosBundleId: 'com.Toq.lacrosseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_02t5aoIlu6Tk-Aq1haDdU_VVc8i9kxU',
    appId: '1:969831362695:web:28b53005bbd92765108822',
    messagingSenderId: '969831362695',
    projectId: 'lacrooseapp',
    authDomain: 'lacrooseapp.firebaseapp.com',
    storageBucket: 'lacrooseapp.firebasestorage.app',
    measurementId: 'G-7C9KZ15R4L',
  );
}
