// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANL40C9XN0vDO4WJRHYUTn7A878d7kiJg',
    appId: '1:966185766887:web:7278f765ff45da2994f742',
    messagingSenderId: '966185766887',
    projectId: 'lacrosse-app-ec697',
    authDomain: 'lacrosse-app-ec697.firebaseapp.com',
    databaseURL: 'https://lacrosse-app-ec697-default-rtdb.firebaseio.com',
    storageBucket: 'lacrosse-app-ec697.firebasestorage.app',
    measurementId: 'G-1M44MJEND9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9P2V8E6MxKgzACah38sJSBpugVhDp1b0',
    appId: '1:966185766887:android:ccc1e74b693bf31d94f742',
    messagingSenderId: '966185766887',
    projectId: 'lacrosse-app-ec697',
    databaseURL: 'https://lacrosse-app-ec697-default-rtdb.firebaseio.com',
    storageBucket: 'lacrosse-app-ec697.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACG-vb0vi8Uj7QcUBvp1sfkYk3uL6J-Xs',
    appId: '1:966185766887:ios:1bdccf794a87669294f742',
    messagingSenderId: '966185766887',
    projectId: 'lacrosse-app-ec697',
    databaseURL: 'https://lacrosse-app-ec697-default-rtdb.firebaseio.com',
    storageBucket: 'lacrosse-app-ec697.firebasestorage.app',
    iosBundleId: 'com.example.lacrosse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACG-vb0vi8Uj7QcUBvp1sfkYk3uL6J-Xs',
    appId: '1:966185766887:ios:1bdccf794a87669294f742',
    messagingSenderId: '966185766887',
    projectId: 'lacrosse-app-ec697',
    databaseURL: 'https://lacrosse-app-ec697-default-rtdb.firebaseio.com',
    storageBucket: 'lacrosse-app-ec697.firebasestorage.app',
    iosBundleId: 'com.example.lacrosse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANL40C9XN0vDO4WJRHYUTn7A878d7kiJg',
    appId: '1:966185766887:web:721eb224f544164d94f742',
    messagingSenderId: '966185766887',
    projectId: 'lacrosse-app-ec697',
    authDomain: 'lacrosse-app-ec697.firebaseapp.com',
    databaseURL: 'https://lacrosse-app-ec697-default-rtdb.firebaseio.com',
    storageBucket: 'lacrosse-app-ec697.firebasestorage.app',
    measurementId: 'G-CNLN7KM6QR',
  );
}
